# Generated by Django 3.1.1 on 2020-09-30 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200928_1418'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
